https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

# Tensor
- pytorchはモデルの入出力やパラメータにTensorを利用する
- Numpyとの違いはGPUや他のハードウェアアクセラレータ上で実行できる点
- Numpyと同じメモリを共有することができるのでデータのコピーが不要

In [4]:
import torch
import numpy as np

## Initializing a Tensor
Tensorの初期化の方法をまとめる

### listを使ってTensorを初期する

In [7]:
data = [[1, 2],[3, 4]]
torch.tensor(data)

tensor([[1, 2],
        [3, 4]])

### NumPyを使ってTensorを初期化する

In [8]:
np_array = np.array([[1, 2],[3, 4]])
torch.from_numpy(np_array)

tensor([[1, 2],
        [3, 4]])

### 他のTensorをつかってTendorを初期化する

In [14]:
base_tensor = torch.tensor([[1, 2],[3, 4]])
base_tensor

tensor([[1, 2],
        [3, 4]])

In [18]:
# 基のTensorのshape、データ型（int）で初期化
torch.ones_like(base_tensor)

tensor([[1, 1],
        [1, 1]])

In [19]:
# データ型をfloatにオーバーライドして初期化
torch.ones_like(base_tensor, dtype=torch.float)

tensor([[1., 1.],
        [1., 1.]])

In [28]:
# 要素がすべて1の行列
ones_tensor = torch.ones(base_tensor.shape)

# 要素がすべて0の行列
zeros_tensor = torch.zeros(base_tensor.shape)

# 要素の値がランダム値の行列
rand_tensor = torch.rand(base_tensor.shape)

print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor} \n")
print(f"Random Tensor: \n{rand_tensor}")

Ones Tensor: 
tensor([[1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0.],
        [0., 0.]]) 

Random Tensor: 
tensor([[0.7685, 0.0611],
        [0.1794, 0.2388]])


## Attributes of a Tensor
Tensorが持つ属性をまとめる

In [27]:
# 検証用のTensorを準備
tensor = torch.rand(3,4)
tensor

tensor([[0.6545, 0.8768, 0.6438, 0.4188],
        [0.8603, 0.7758, 0.0749, 0.7015],
        [0.6159, 0.2530, 0.3408, 0.3100]])

Tensorの形状は`shape`で取得できる

In [29]:
tensor.shape

torch.Size([3, 4])

Tensorの値の型は`dtype`で取得できる

In [31]:
tensor.dtype

torch.float32

利用しているデバイスは`device`で確認できる

In [32]:
tensor.device

device(type='cpu')

GPUが利用可能かどうかは`toch.cuda.is_available()`で確認できる

In [33]:
torch.cuda.is_available()

True

GPUには下記のように`to`で移動できる

In [34]:
if torch.cuda.is_available():
    gpu_tensor = tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

## Operations on Tensors

### 要素の抽出
Numpyのように要素の抽出をすることができる

In [60]:
# 1行目の取得
tensor[0]

tensor([0.6545, 0.0000, 0.6438, 0.4188])

In [61]:
# 最終行の取得
tensor[-1]

tensor([0.6159, 0.0000, 0.3408, 0.3100])

In [62]:
# 1列目の取得
tensor[:, 0]

tensor([0.6545, 0.8603, 0.6159])

In [63]:
# 最終列の取得
tensor[:, -1]

tensor([0.4188, 0.7015, 0.3100])

### 要素の更新

In [64]:
# 2列目の値を0にする
tensor[:, 1] = 0
tensor

tensor([[0.6545, 0.0000, 0.6438, 0.4188],
        [0.8603, 0.0000, 0.0749, 0.7015],
        [0.6159, 0.0000, 0.3408, 0.3100]])

### 連結

In [58]:
# 行として連結（6行4列）
torch.cat([tensor, tensor], dim=0)

tensor([[0.6545, 0.0000, 0.6438, 0.4188],
        [0.8603, 0.0000, 0.0749, 0.7015],
        [0.6159, 0.0000, 0.3408, 0.3100],
        [0.6545, 0.0000, 0.6438, 0.4188],
        [0.8603, 0.0000, 0.0749, 0.7015],
        [0.6159, 0.0000, 0.3408, 0.3100]])

In [59]:
# 列として連結（3行8列）
torch.cat([tensor, tensor], dim=1)

tensor([[0.6545, 0.0000, 0.6438, 0.4188, 0.6545, 0.0000, 0.6438, 0.4188],
        [0.8603, 0.0000, 0.0749, 0.7015, 0.8603, 0.0000, 0.0749, 0.7015],
        [0.6159, 0.0000, 0.3408, 0.3100, 0.6159, 0.0000, 0.3408, 0.3100]])

### 算術演算

#### 転置行列
行列の行と列を入れ替えたものを転置行列と呼び`T`で求められる

In [72]:
tensor.T

tensor([[0.6545, 0.8603, 0.6159],
        [0.0000, 0.0000, 0.0000],
        [0.6438, 0.0749, 0.3408],
        [0.4188, 0.7015, 0.3100]])

#### 積
行列の積の演算は`@`または`matmul`を利用することで求められる

In [70]:
tensor @ tensor.T

tensor([[1.0182, 0.9050, 0.7523],
        [0.9050, 1.2378, 0.7728],
        [0.7523, 0.7728, 0.5916]])

In [71]:
tensor.matmul(tensor.T)

tensor([[1.0182, 0.9050, 0.7523],
        [0.9050, 1.2378, 0.7728],
        [0.7523, 0.7728, 0.5916]])

#### 要素同士の積
行列の要素同士をかけた行列は`*`または`mul`で求められる

In [73]:
tensor * tensor

tensor([[0.4283, 0.0000, 0.4145, 0.1754],
        [0.7401, 0.0000, 0.0056, 0.4921],
        [0.3793, 0.0000, 0.1161, 0.0961]])

In [74]:
tensor.mul(tensor)

tensor([[0.4283, 0.0000, 0.4145, 0.1754],
        [0.7401, 0.0000, 0.0056, 0.4921],
        [0.3793, 0.0000, 0.1161, 0.0961]])

### 1要素のTensor
`sum`, `max`, `min`などで1要素のテンソルがある場合、`item()`を使って数値に変換することができる

In [91]:
tensor.sum()

tensor(4.6204)

In [93]:
type(tensor.sum())

torch.Tensor

In [92]:
tensor.sum().item()

4.620437145233154

In [94]:
type(tensor.sum().item())

float

### インプレース（破壊的変更）
演算結果をオペランド（被演算子）に格納するような処理をインプレースと呼び、接尾辞として`_`が付く

In [98]:
ones_tensor = torch.ones(3, 4)
ones_tensor[:, 1] = 0
ones_tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

あるTensorに`add`を実行結果は、元のTensorのすべての要素に値が足された別のTensorが返却され、元のTensorは変化しない

In [99]:
ones_tensor.add(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [100]:
ones_tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

インプレースである`add_`を実行すると、実行結果は`add`の結果と変わらないが、元のTensor自体が変化する

In [101]:
ones_tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [102]:
ones_tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

## Bridge with NumPy
CPU上のTensorとNumpyはメモリ位置を共有することができ、一方を変更することで他方を変更することができる

#### TensorからNumpy

In [104]:
t = torch.ones(5)
n = t.numpy()

In [105]:
t.add_(5)

tensor([6., 6., 6., 6., 6.])

In [106]:
n

array([6., 6., 6., 6., 6.], dtype=float32)

#### NumpyからTensor

In [108]:
n = np.ones(5)
t = torch.from_numpy(n)

In [109]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [110]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)